#################################################################################################################
### Exercise lecture 3: Github workflows                                                                      ###
###  - Repo: https://github.com/kytcrystal/lecture3-github-workflow-project/actions/runs/6725227588/workflow  ###
###  - Authors: Crystal Kwok & Matteo Ponza                                                                   ###
#################################################################################################################

name: Measure coverage
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          architecture: x64

      - name: Run Coverage and Test Report
        run: ./gradlew jacocoTestReport

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/**/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60